// src/components/Orders/mockBaristaOrders.js

export const MOCK_BARISTA_ORDERS = [
  {
    id: 'mock-barista-101',
    numeracion: '101',
    direccion: 'Mesa 4 (Salón)',
    hora: '18:35',
    created: new Date(Date.now() - 4 * 60000).toISOString(),
    method: 'Efectivo',
    pago: 4500,
    total: 4500,
    items: [
      {
        id: 'mock-item-1',
        name: 'Latte',
        category: 'Cafetería',
        quantity: 1,
        size: 'Plus (12oz)',
        extras: ['Leche Almendras (+$500)', 'Extra Shot (+$300)'],
        vaso: 'Stephan',
        price: 2800,
      },
      {
        id: 'mock-item-2',
        name: 'Medialuna de Manteca',
        category: 'Cafetería',
        quantity: 2,
        price: 850,
      },
      {
        id: 'mock-item-3',
        name: '1/4 KG Helado',
        category: 'Helados',
        sabores: ['Dulce de Leche Granizado', 'Tramontana'],
        quantity: 1,
        price: 3500,
      },
    ],
  },
  {
    id: 'mock-barista-102',
    numeracion: '102',
    direccion: 'Retiro en Barra',
    hora: '18:40',
    created: new Date(Date.now() - 2 * 60000).toISOString(),
    method: 'MercadoPago',
    pago: 3200,
    total: 3200,
    items: [
      {
        id: 'mock-item-4',
        name: 'Capuchino',
        category: 'Cafetería',
        quantity: 1,
        size: 'Mini (8oz)',
        extras: ['Canela Extra (+$150)'],
        vaso: 'Lucía',
        price: 1900,
      },
      {
        id: 'mock-item-5',
        name: 'Iced Caramel Macchiato',
        category: 'Cafetería',
        quantity: 1,
        size: 'Ultra (16oz)',
        extras: ['Doble Caramelo (+$400)'],
        vaso: 'Emi',
        price: 2900,
      },
    ],
  },
  {
    id: 'mock-barista-103',
    numeracion: '103',
    direccion: 'Delivery (Av. San Martín 450)',
    hora: '18:42',
    created: new Date().toISOString(),
    method: 'Transferencia',
    pago: 5100,
    total: 5100,
    items: [
      {
        id: 'mock-item-6',
        name: 'Flat White',
        category: 'Cafetería',
        quantity: 2,
        size: 'Plus (12oz)',
        extras: [],
        vaso: 'Carlos',
        price: 2200,
      },
      {
        id: 'mock-item-7',
        name: 'Tostado de Jamón y Queso',
        category: 'Cafetería',
        quantity: 1,
        price: 2800,
      },
    ],
  },
  {
    id: 'mock-barista-104',
    numeracion: '104',
    direccion: 'Mesa 2 (Patio)',
    hora: '18:45',
    created: new Date().toISOString(),
    method: 'MercadoPago',
    pago: 7000,
    total: 7000,
    items: [
      {
        id: 'mock-item-8',
        name: 'Frappé Oreo',
        category: 'Cafetería',
        quantity: 1,
        size: 'Plus (12oz)',
        extras: ['Crema Chantilly Extra (+$300)'],
        vaso: 'Martina',
        price: 3400,
      },
      {
        id: 'mock-item-9',
        name: 'Frappé Dulce de Leche',
        category: 'Cafetería',
        quantity: 1,
        size: 'Ultra (16oz)',
        extras: ['Salsa Extra (+$200)'],
        vaso: 'Felipe',
        price: 3600,
      },
    ],
  },
];
